### ISSUE TITLE
Puppet version compatibility

### ISSUE THREAD

**Issue by dazole** [binford2k/puppet-assert#5]
Per metadata.json, puppet version compatibility stops at puppet v5:
`"version_requirement": ">=3.0.0 <5.0.0"`

Does it work with versions higher, and if so, can metadata.json be updated?

**Comment by dazole** [comment]
Just to follow up, I tested this on OSS puppet 5.5.10 and it worked fine.  I might have a PR coming soon for a `symlink` check, too

**Comment by binford2k** [comment]
resolved
